//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoDuyDat_QLQuanGame_CDTH17.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietBi
    {
        public string ID_PC { get; set; }
        public string ID_User { get; set; }
        public string Stime { get; set; }
        public string Etime { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
